// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWXUFOxxR6x9D1f2frV_VHzG0ipGcekYM',
    appId: '1:674721421631:web:4ba18327ea7cb294d35b8a',
    messagingSenderId: '674721421631',
    projectId: 'dymwa-b2af2',
    authDomain: 'dymwa-b2af2.firebaseapp.com',
    storageBucket: 'dymwa-b2af2.firebasestorage.app',
    measurementId: 'G-0DZCD42V8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFL3-WmxiolCWVhpOq2WHIC5TTmFvboRw',
    appId: '1:674721421631:android:3d4b9bbe1ad0971bd35b8a',
    messagingSenderId: '674721421631',
    projectId: 'dymwa-b2af2',
    storageBucket: 'dymwa-b2af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLWHkY11_7-nUHQI1LhK-Kwba_WGaY3og',
    appId: '1:674721421631:ios:c400091b9e4d29ded35b8a',
    messagingSenderId: '674721421631',
    projectId: 'dymwa-b2af2',
    storageBucket: 'dymwa-b2af2.firebasestorage.app',
    iosBundleId: 'com.example.dymwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLWHkY11_7-nUHQI1LhK-Kwba_WGaY3og',
    appId: '1:674721421631:ios:c400091b9e4d29ded35b8a',
    messagingSenderId: '674721421631',
    projectId: 'dymwa-b2af2',
    storageBucket: 'dymwa-b2af2.firebasestorage.app',
    iosBundleId: 'com.example.dymwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWXUFOxxR6x9D1f2frV_VHzG0ipGcekYM',
    appId: '1:674721421631:web:83f532e4cd47754ad35b8a',
    messagingSenderId: '674721421631',
    projectId: 'dymwa-b2af2',
    authDomain: 'dymwa-b2af2.firebaseapp.com',
    storageBucket: 'dymwa-b2af2.firebasestorage.app',
    measurementId: 'G-V2B6L6K75T',
  );
}
